extends Node

signal coin_collected
signal run_started
signal finish_reached
signal run_ended(seconds)

signal ui_requested_load_track
signal ui_requested_start_run
signal ui_requested_select_track_screen
signal ui_requested_next_environment
signal ui_requested_previous_environment
signal ui_requested_next_marble
signal ui_requested_previous_marble
